name: BukkitGroovy
version: ${project.version}
main: eu.mikroskeem.debug.bukkitgroovy.Main
authors: [mikroskeem]
description: Evaluate Groovy script with a command
website: https://mikroskeem.eu
softdepend:
- ProvidersLib

commands:
  groovyscript:
    description: §8§l[§a§lBG§8§l]§7 Evaluate Groovy script
    permission: bukkitgroovy.use
    usage: §8/§a<command> §8[§acode§8]
    aliases:
    - groovy
    - gr